version: "3.2"
services:
  app:
    image: node:16.13.2-alpine3.14
    command: "npm start"
    restart: unless-stopped
    working_dir: /usr/src
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src
    ports:
      - 3000:3000
